language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
bundler_args: --without integration development
script:
  - bundle ex foodcritic -f any --tags ~FC001 .
  - bundle ex rspec --color --format progress
  - bundle ex rubocop
notifications:
  email:
    on_success: never  # default: change
    on_failure: always # default: always
